spring:
  datasource:
    platform: oracle
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/pdborcl
    username: root
    password: 123456
    druid:
      test-while-idle: true
      test-on-borrow: true
      max-pool-prepared-statement-per-connection-size: 20
      min-idle: 5

