server:
  port: 8848
  servlet:
    context-path: /nacos
#  tomcat:
#    accesslog:
#      enabled: true
#      pattern: "%h %l %u %t %r %s %b %D"
#      directory: ${LOGGING_PATH:/data/apps/logs/nacos}

spring:
  application:
    name: nacos
  mvc:
    view:
      suffix: .jsp
      prefix: /jsp/
  profiles:
    active:  ${SPRING_PROFILES_ACTIVE:uat}


mybatis-plus:
  global-config:
    db-config:
      db-type: oracle
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      table-underline: true
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-prefix: mybatis.sql.

#logging:
#  path: nacosconf/logs
#  config: classpath:logback-spring.xml

#/data/apps/logs/nacos/logs
nacos:
  logs:
    path: ${LOGGING_PATH:logs}
  standalone: false
  cmdb:
    dumpTaskInterval: 3600
    eventTaskInterval: 10
    labelTaskInterval: 300
    loadDataAtStart: false
  security:
    ignore:
      urls: /,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/login,/v1/console/health/**,/v1/cs/**,/v1/ns/**,/v1/cmdb/**,/actuator/**,/v1/console/server/**
  maxHealthCheckFailCount: 12
  isHealthCheck: false
  notifySocketTimeout: 8000
  notifyConnectTimeout: 20
  isQuickStart: false
  openInnerInterfaceFilter: false
  useAddressServer: true

management:
  metrics:
    export:
      influx:
        enable: false
      elastic:
        enabled: false
